homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20.29
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Mobile app
mobile_app:

# Logging
logger:
    default: warning
    logs:
        homeassistant.components.python_script: debug
# Security
http:
    ip_ban_enabled: true
    login_attempts_threshold: 10
    ssl_certificate: /home/kganguly/external_access/dehydrated/certs/ganguly.duckdns.org/fullchain.pem
    ssl_key: /home/kganguly/external_access/dehydrated/certs/ganguly.duckdns.org/privkey.pem
    base_url: !secret external_url
    use_x_forwarded_for: true
    trusted_proxies:
        - 127.0.0.1
        - ::1
        - 192.168.1.1

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# System Health
system_health:

# Sensor suite
sensor:
  - platform: darksky
    api_key: !secret darksky_secret
    name: "Forecast"
    units: si
    scan_interval: '00:15'
    monitored_conditions:
    - summary
    - icon
    - temperature_high
    - temperature_low 
    - temperature
    - humidity
    - pressure
    - wind_speed
    - visibility
    - precip_probability
  - platform: time_date
    display_options:
    - 'time'
    - 'date'
  - platform: systemmonitor
    resources:
        - type: memory_use_percent
        - type: processor_use
  - platform: mqtt
    state_topic: "sensor/room/temperature"
    name: "Room Temperature"
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: "sensor/room/humidity"
    name: "Room Humidity"
    unit_of_measurement: "%"
  - platform: template
    sensors:
        kanishka_battery:
            value_template: "{{ state_attr('device_tracker.kganguly_gangulyphone', 'battery_level') }}"
            unit_of_measurement: '%'
            friendly_name: "Kanishka Battery"
 
        shruti_battery:
            value_template: "{{ state_attr('device_tracker.sagarwal_shrutiphone', 'battery_level') }}"
            unit_of_measurement: '%'
            friendly_name: "Shruti Battery"

# Speed test          
speedtestdotnet:
    server_id: 20229

# Wyze Cams
ffmpeg:
camera:
    - platform: ffmpeg
      input: -rtsp_transport udp -i rtsp://kganguly:Blackfoot@192.168.1.69/live
      name: Kitchen Cam
    
    - platform: ffmpeg
      input: -rtsp_transport udp -i rtsp://kganguly:Blackfoot@192.168.1.154/live
      name: Stairs Cam
    
    - platform: local_file
      file_path: /home/kganguly/.homeassistant/images/mail_and_packages/mail_image/mail_today.gif
      name: Mail Cam

# MQTT
mqtt:
    broker: 192.168.1.167
    username: kganguly
    password: !secret mqtt_secret

weather:
  - platform: darksky
    api_key: !secret darksky_secret
    name: "Weather"
    units: si

# Thermostat
nest:
  client_id: 9f07bb33-513d-41ba-a09c-dedac6dfbaf7
  client_secret: !secret nest_secret
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Eufy
eufy:
  username: kanishkaganguly2002@gmail.com
  password: !secret eufy_pass

# TP-Link
tplink:

# IFTTT
ifttt:
  key: !secret ifttt_key

# Emulated Hue
emulated_hue:
  host_ip: 192.168.1.167
  listen_port: 80
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - switch
  entities:
    switch.lamp:
      name: "Lamp"
    light.light_one:
      name: "Light One"
    light.light_two:
      name: "Light Two"
    switch.gangulybeast:
      name: "GangulyBeast"

# Wake on LAN
switch:
    - platform: wake_on_lan
      mac: "e0:d5:5e:a6:3b:fe"
      host: "192.168.1.72"
      name: "gangulybeast"

# Media Players
media_player:
    - platform: plex
      show_all_controls: false
      remove_unavailable_clients: true
      client_remove_interval: 300
spotify: 
    client_id: 8b787871eea342a49263f53829b38a30
    client_secret: !secret spotify_secret

# Groups
light:
  - platform: group
    name: Ceiling Lights
    entities:
      - light.light_one
      - light.light_two

# Zones
zone:
    - name: Home
      latitude: !secret home_lat
      longitude: !secret home_long
      radius: 250
      icon: mdi:home
    - name: Work
      latitude: !secret work_lat
      longitude: !secret work_long
      radius: 250
      icon: mdi:briefcase

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chat_id
notify:
  - name: GangulyAssistant
    platform: telegram
    chat_id: !secret telegram_chat_id

# Python scripts
python_script:
# Other configs
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
